import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Package, Droplets, Wind, Store, Truck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import { SERVICE_PRICES } from "@/lib/constants";
import { toast } from "sonner";

const serviceOptions = [
  { value: "wash_and_fold", label: "Wash & Fold", icon: Package },
  { value: "dry_clean", label: "Dry Clean", icon: Droplets },
  { value: "ironing", label: "Ironing", icon: Wind },
] as const;

const fulfillmentOptions = [
  { value: "pickup", label: "Pick-up", icon: Store },
  { value: "delivery", label: "Delivery", icon: Truck },
] as const;

export default function NewOrder() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [customerName, setCustomerName] = useState("");
  const [customerPhone, setCustomerPhone] = useState("");
  const [serviceType, setServiceType] = useState<string>("wash_and_fold");
  const [weight, setWeight] = useState("");
  const [weightUnit, setWeightUnit] = useState<"lbs" | "kg">("lbs");
  const [fulfillmentType, setFulfillmentType] = useState<string>("pickup");
  const [instructions, setInstructions] = useState("");

  const calculatedPrice = weight ? (parseFloat(weight) * (SERVICE_PRICES[serviceType] || 2)).toFixed(2) : "0.00";

  const createOrder = useMutation({
    mutationFn: async () => {
      // Create or find customer
      let customerId: string;
      const { data: existing } = await supabase
        .from("customers")
        .select("id")
        .eq("name", customerName)
        .eq("phone", customerPhone || "")
        .maybeSingle();

      if (existing) {
        customerId = existing.id;
      } else {
        const { data: newCustomer, error: custError } = await supabase
          .from("customers")
          .insert({ name: customerName, phone: customerPhone || null })
          .select("id")
          .single();
        if (custError) throw custError;
        customerId = newCustomer.id;
      }

      // Create order (order_number is auto-generated by trigger)
      const { error } = await supabase.from("orders").insert({
        order_number: "TEMP", // Will be overwritten by trigger
        customer_id: customerId,
        service_type: serviceType as any,
        weight: parseFloat(weight) || 0,
        weight_unit: weightUnit as any,
        price: parseFloat(calculatedPrice),
        fulfillment_type: fulfillmentType as any,
        special_instructions: instructions || null,
      });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["orders"] });
      toast.success("Order created successfully");
      navigate("/");
    },
    onError: (e) => {
      console.error(e);
      toast.error("Failed to create order");
    },
  });

  const canSubmit = customerName.trim() && weight && parseFloat(weight) > 0;

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-card border-b px-4 py-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <h1 className="text-lg font-bold">New Order</h1>
          </div>
          <Button variant="ghost" onClick={() => navigate(-1)}>Cancel</Button>
        </div>
      </header>

      <main className="p-4 space-y-5 max-w-lg mx-auto pb-8">
        {/* Customer */}
        <div className="space-y-3">
          <Label className="text-sm font-semibold">Customer</Label>
          <Input
            placeholder="Customer name"
            value={customerName}
            onChange={(e) => setCustomerName(e.target.value)}
          />
          <Input
            placeholder="Phone number (optional)"
            value={customerPhone}
            onChange={(e) => setCustomerPhone(e.target.value)}
          />
        </div>

        {/* Service Type */}
        <div className="space-y-3">
          <Label className="text-sm font-semibold">Service Type</Label>
          <div className="grid grid-cols-3 gap-2">
            {serviceOptions.map((opt) => (
              <Card
                key={opt.value}
                className={cn(
                  "p-3 cursor-pointer text-center transition-all",
                  serviceType === opt.value
                    ? "border-primary bg-primary/5 ring-1 ring-primary"
                    : "hover:border-primary/50"
                )}
                onClick={() => setServiceType(opt.value)}
              >
                <opt.icon className={cn("h-5 w-5 mx-auto mb-1", serviceType === opt.value ? "text-primary" : "text-muted-foreground")} />
                <p className="text-xs font-medium">{opt.label}</p>
              </Card>
            ))}
          </div>
        </div>

        {/* Weight */}
        <div className="space-y-3">
          <Label className="text-sm font-semibold">Weight</Label>
          <div className="flex gap-2">
            <Input
              type="number"
              placeholder="0.0"
              value={weight}
              onChange={(e) => setWeight(e.target.value)}
              className="flex-1"
              min="0"
              step="0.1"
            />
            <div className="flex rounded-md border overflow-hidden">
              {(["lbs", "kg"] as const).map((unit) => (
                <button
                  key={unit}
                  onClick={() => setWeightUnit(unit)}
                  className={cn(
                    "px-4 py-2 text-sm font-medium transition-colors",
                    weightUnit === unit
                      ? "bg-primary text-primary-foreground"
                      : "bg-card text-muted-foreground hover:bg-secondary"
                  )}
                >
                  {unit.toUpperCase()}
                </button>
              ))}
            </div>
          </div>
          {weight && parseFloat(weight) > 0 && (
            <p className="text-sm text-muted-foreground">
              Estimated price: <span className="font-semibold text-foreground">${calculatedPrice}</span>
            </p>
          )}
        </div>

        {/* Fulfillment */}
        <div className="space-y-3">
          <Label className="text-sm font-semibold">Fulfillment</Label>
          <div className="grid grid-cols-2 gap-2">
            {fulfillmentOptions.map((opt) => (
              <Card
                key={opt.value}
                className={cn(
                  "p-3 cursor-pointer text-center transition-all",
                  fulfillmentType === opt.value
                    ? "border-primary bg-primary/5 ring-1 ring-primary"
                    : "hover:border-primary/50"
                )}
                onClick={() => setFulfillmentType(opt.value)}
              >
                <opt.icon className={cn("h-5 w-5 mx-auto mb-1", fulfillmentType === opt.value ? "text-primary" : "text-muted-foreground")} />
                <p className="text-xs font-medium">{opt.label}</p>
              </Card>
            ))}
          </div>
        </div>

        {/* Instructions */}
        <div className="space-y-3">
          <Label className="text-sm font-semibold">Special Instructions</Label>
          <Textarea
            placeholder="Any special requests..."
            value={instructions}
            onChange={(e) => setInstructions(e.target.value)}
            rows={3}
          />
        </div>

        {/* Submit */}
        <Button
          className="w-full h-12 text-base font-semibold"
          disabled={!canSubmit || createOrder.isPending}
          onClick={() => createOrder.mutate()}
        >
          {createOrder.isPending ? "Creating..." : "Create Order"}
        </Button>
      </main>
    </div>
  );
}
